import test from 'node:test';
import assert from 'node:assert/strict';
import { addTask, createTask, filterTasks, loadTasks, PRIORITIES, STORAGE_KEY, setTaskStatus, updateTask } from '../src/task-domain.js';

function storage() { const data = new Map(); return { getItem: (key) => data.get(key) ?? null, setItem: (key, value) => data.set(key, value) }; }

test('cadastra uma tarefa válida com valores normalizados', () => { const task = createTask({ title: '  Estudar  ', description: '  capítulo 1 ', priority: 'alta' }, new Date('2026-01-01')); assert.equal(task.title, 'Estudar'); assert.equal(task.description, 'capítulo 1'); assert.equal(task.priority, 'alta'); assert.equal(task.status, 'pendente'); assert.equal(task.createdAt, '2026-01-01T00:00:00.000Z'); assert.ok(task.id); });
test('rejeita título vazio e limites inválidos', () => { assert.throws(() => createTask({ title: '   '}), /título/); assert.throws(() => createTask({ title: 'a'.repeat(101)}), /100/); assert.throws(() => createTask({ title: 'ok', description: 'a'.repeat(501)}), /500/); });
test('usa média como padrão e aceita apenas prioridades permitidas', () => { assert.equal(createTask({ title: 'Tarefa' }).priority, 'media'); for (const priority of PRIORITIES) assert.equal(createTask({ title: 'Tarefa', priority }).priority, priority); assert.throws(() => createTask({ title: 'Tarefa', priority: 'urgente' }), /prioridade/); });
test('persiste tarefas, cria IDs únicos e preserva anteriores', () => { const store = storage(); const first = addTask(store, { title: 'Primeira' }, new Date('2026-01-01')); const second = addTask(store, { title: 'Segunda' }, new Date('2026-01-02')); const tasks = loadTasks(store); assert.equal(tasks.length, 2); assert.notEqual(first.id, second.id); assert.equal(tasks[0].status, 'pendente'); assert.equal(JSON.parse(store.getItem(STORAGE_KEY)).length, 2); });
test('edita somente a tarefa selecionada e preserva metadados', () => { const store = storage(); const first = addTask(store, { title: 'Primeira' }, new Date('2026-01-01')); const second = addTask(store, { title: 'Segunda', priority: 'alta' }, new Date('2026-01-02')); const updated = updateTask(store, first.id, { title: '  Atualizada  ', description: 'Detalhes', priority: 'baixa' }); const tasks = loadTasks(store); assert.equal(updated.id, first.id); assert.equal(updated.createdAt, first.createdAt); assert.equal(updated.status, 'pendente'); assert.equal(updated.title, 'Atualizada'); assert.equal(updated.priority, 'baixa'); assert.deepEqual(tasks[1], second); });
test('rejeita edição inválida sem alterar a tarefa', () => { const store = storage(); const task = addTask(store, { title: 'Original' }); assert.throws(() => updateTask(store, task.id, { title: '   ', priority: 'media' }), /título/); assert.equal(loadTasks(store)[0].title, 'Original'); });
test('alterna conclusão, preserva os demais dados e persiste', () => { const store = storage(); const first = addTask(store, { title: 'Primeira', description: 'Detalhes', priority: 'alta' }, new Date('2026-01-01')); const second = addTask(store, { title: 'Segunda' }); const completed = setTaskStatus(store, first.id, 'concluida'); assert.equal(completed.status, 'concluida'); assert.equal(completed.title, first.title); assert.deepEqual(loadTasks(store)[1], second); assert.equal(setTaskStatus(store, first.id, 'pendente').status, 'pendente'); assert.equal(loadTasks(store)[0].status, 'pendente'); });
test('rejeita status inválido e tarefa inexistente', () => { const store = storage(); const task = addTask(store, { title: 'Tarefa' }); assert.throws(() => setTaskStatus(store, task.id, 'cancelada'), /Status/); assert.throws(() => setTaskStatus(store, 'missing', 'concluida'), /não encontrada/); });
test('filtra tarefas por status sem alterar os dados', () => { const tasks = [{ id: '1', status: 'pendente' }, { id: '2', status: 'concluida' }]; assert.deepEqual(filterTasks(tasks), tasks); assert.deepEqual(filterTasks(tasks, 'pendentes'), [tasks[0]]); assert.deepEqual(filterTasks(tasks, 'concluidas'), [tasks[1]]); assert.deepEqual(filterTasks(tasks, 'invalido'), tasks); });
test('trata localStorage inválido sem quebrar o fluxo', () => { const broken = { getItem: () => '{invalid json' }; assert.deepEqual(loadTasks(broken), []); });
